---
format: 
  html: 
    fontsize: 1.3em
---

<div class="box">
Compte tenu de ma spécialisation en gestion des risques, les contenus que je prévois de partager dans cette section dédiée à la 3ème année (3A) porteront principalement sur les enseignements spécifiques à cette spécialisation. Je m'efforcerai de rendre ces partages aussi pertinents et enrichissants que possible, en espérant qu'ils serviront de guide précieux pour ceux qui suivront une voie similaire.
</div>


# Ressources pour les Étudiants de l’ENSAI (1A, 2A, 3A GDR)

Dans cette section, vous trouverez une sélection de **cours, TD et devoirs sur table** de l’ENSAI pour la 1ʳᵉ, 2ᵉ et 3ᵉ année, en particulier pour la filière **GDR (Gestion des Risques)**.

## **Accédez directement aux ressources partagées :**
[Dossier Google Drive – Cours, TD, Projets et Sujets d’Examens](https://drive.google.com/drive/folders/1oMynXldXVaO_FXX2XmVwRbKgztfsVsR1?usp=sharing)

* **1ʳᵉ année :** le contenu est encore peu enrichi. Nous comptons sur vous pour y ajouter des informations utiles afin d’aider les prochaines promotions.
* **2ᵉ année :** la base existe mais reste à compléter. Nous espérons que les étudiants de 2A penseront à l’enrichir davantage.
* **3ᵉ année (GDR) :** nous avons fait un effort particulier pour rassembler les cours, TD et sujets importants. Vous y trouverez notamment des **anciens sujets et corrigés de calcul stochastique**. Nous espérons que cette initiative se poursuivra et que les étudiants des autres filières feront de même.

## **Quelques Projets de la 3ᵉ année GDR :**

Découvrez les projets et travaux réalisés par Cheryl lors de sa 3ᵉ année GDR à l’ENSAI :
[💻 Site personnel de Cheryl](https://cheryl-kdio.github.io/personal-website/)

::: callout-warning
## ⚠️ Avertissement important
**Respect des droits d’auteur :**  
Il est interdit de **photocopier, numériser ou diffuser** les supports de cours des professeurs sans leur autorisation.  
Ces documents sont protégés par le **droit de propriété intellectuelle** et font partie d’un processus pédagogique précis.  
Toute diffusion non autorisée peut avoir des **conséquences juridiques**.
:::

